name = "umda-tauri-update-server"
workers_dev = true
compatibility_date = "2023-11-25"
main = "src/main.ts"

[vars]
GITHUB_ACCOUNT = 'aravindhnivas'
GITHUB_REPO = 'UMDA_UI'
GITHUB_TOKEN = ''                # Optional - used with private repos

[build]
command = "pnpm install && pnpm build"
