name = "umdaui-update-server"
type = "webpack"
zone_id = ""
account_id = ""
route = ""
workers_dev = true
compatibility_date = "2022-03-26"

[vars]
GITHUB_ACCOUNT = 'aravindhnivas'
GITHUB_REPO = 'UMDA_UI'
GITHUB_TOKEN = ''                # Optional - used with private repos

[build]
command = "pnpm install && pnpm build"

[build.upload]
format = "service-worker"
